sudo: required
language: julia

os:
    - osx
    - linux

compiler:
    - gcc

env:
  global:
    - LIBSTDC_VERSION=4.8

julia:
    - 0.4
    - nightly

notifications:
    email: false

matrix:
  allow_failures:
    - os: osx # allow OS X to fail until intermittent failures can be resolved.

before_install:
  # Prepare compilers
  - sh scripts/install-gcc.sh

  # Debug information
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then lsb_release -a; fi
  - uname -a

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - xvfb-run julia -e 'Pkg.add("JLD"); Pkg.clone(pwd()); Pkg.build("ElasticFDA")'

after_success:
  - julia -e 'cd(Pkg.dir("ElasticFDA")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
